### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by micahwalter** [jaynguyens/obsidian-ghost-publish#8]
I set this up according to the docs, but when I click the Ghost icon, nothing seems to happen. Is there a log output somewhere?

**Comment by jcsogo** [comment]
Trying to run this in Obsidian v1.1.9 shows this error in the console

```
app.js:1 Uncaught (in promise) Error: Request failed, status 422
    at new t (app.js:1:710073)
    at Aw (app.js:1:710265)
    at app.js:1:710942
    at app.js:1:235505
    at Object.next (app.js:1:235610)
    at a (app.js:1:234349)
```

@micahwalter - you can show the console pressing Shift+Ctrl+i

**Comment by localjo** [comment]
I'm also getting this error. Has anyone found any solutions or ideas?

**Comment by localjo** [comment]
Update: I found that in my case, I had an error in the frontmatter for tags. I had the following format, which does NOT work:

```---
title: Hello, World
tags: update, journal
featured: false
published: true
excerpt: More to come soon
---
```

Changed to this format for the tags, and everything seems to work:

```
---
title: Hello, World
tags:
 - journal
 - update
featured: false
published: true
excerpt: More to come soon
---
```
